### PR TITLE
Use latest version of iconarray (v0.2.1)

### PR DESCRIPTION
**Pull request by victoria-cherkas**
Now using iconarray v0.2.1

### CODE REVIEW

**Comment by victoria-cherkas** [comment]
https://jenkins-mch.cscs.ch/job/iconvis_PR/view/change-requests/job/PR-24/ passes with backend_grid_improvements at sha dde9006bad0d756865b7110603516d8dfe128520

**Comment by victoria-cherkas** [comment]
changed to grib_improvements branch 
test: https://jenkins-mch.cscs.ch/job/IconVis/job/iconvis_PR/view/change-requests/job/PR-24/3/

**Comment by victoria-cherkas** [comment]
Now using iconarray v0.2.1

**Comment by victoria-cherkas** [comment]
launch jenkins

**Comment by victoria-cherkas** [comment]
launch jenkins

**Comment by victoria-cherkas** [comment]
launch jenkins

**Review by AnnikaLau — APPROVED** [review]

**Pull request merged**
