### PR TITLE
Remove duplication in Jenkinsfile

### PR DESCRIPTION
**Pull request by victoria-cherkas**
Create test.sh and setup.sh scripts to be used in Jenkinsfile, reducing code duplication. Same was done already in iconarray.

### CODE REVIEW

**Comment by victoria-cherkas** [comment]
launch jenkins

**Comment by victoria-cherkas** [comment]
launch jenkins

**Comment by victoria-cherkas** [comment]
launch jenkins

**Comment by victoria-cherkas** [comment]
launch jenkins

**Comment by victoria-cherkas** [comment]
launch jenkins

**Comment by victoria-cherkas** [comment]
launch jenkins

**Comment by victoria-cherkas** [comment]
launch jenkins

**Review by AnnikaLau — APPROVED** [review]
Looks good!

**Pull request merged**
